version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
      MYSQL_USER: user
      MYSQL_PASSWORD: todo
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: laravel
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./todo-backend:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: todo_app
      DB_USERNAME: root
      DB_PASSWORD: root
    env_file:
      - ./todo-backend/.env
    depends_on:
      - mysql
    command: >
      sh -c "composer install &&
             php artisan migrate &&
             php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: vue
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./todo-frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
 

volumes:
  mysql_data: